import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Inter, Lora } from "next/font/google";
import { Plus_Jakarta_Sans, JetBrains_Mono } from 'next/font/google';
import "./globals.css";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-serif",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Orbit - AI App Builder",
  description: "Generated by create next app",
  icons: {
    icon: "/orbitmini.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

   
    <html
      lang="en"
      suppressHydrationWarning
    >
       <body className={`${lora.variable} ${dmSans.variable} font-sans`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
       
<Header />
        {children}
        </ThemeProvider>
        </body>
    </html>
     </ClerkProvider>
  );
}
